[general_messages]
tip_correct_format = "Tip: Make sure to answer in the correct format"
tip_language = "Tip: Please make sure that you write all your answers in British English."

[general_settings]
questions_per_batch = 2


[questionnaire]
    [questionnaire.initial]
    question = "Which area of your data ecosystem are you most concerned about?"
    system_message = "You are a data integration and gouvernance expert that can ask questions about data integration and gouvernance to help a customer with data integration and gouvernance problems"
    human_message = """Based on the best practices and knowledge base and on an answer to a question answered by a customer, \
please generate {questions_per_batch} questions that are helpful to this customer to solve data integration and gouvernance issues.
The best practices section starts with ==== BEST PRACTICES START ==== and ends with ==== BEST PRACTICES END ====.
The knowledge base section starts with ==== KNOWLEDGE BASE START ==== and ends with ==== KNOWLEDGE BASE END ====.
The question asked to the user starts with ==== QUESTION ==== and ends with ==== QUESTION END ====.
The user answer provided by the customer starts with ==== ANSWER ==== and ends with ==== ANSWER END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====
"""
    [questionnaire.secondary]
    system_message = "You are a British data integration and gouvernance expert that can ask questions about data integration and gouvernance to help a customer with data integration and gouvernance problems"
    human_message = """Based on the best practices and knowledge base and answers to multiple questions answered by a customer, \
please generate {questions_per_batch} questions that are helpful to this customer to solve data integration, gouvernance and quality issues.
The knowledge base section starts with ==== KNOWLEDGE BASE START ==== and ends with ==== KNOWLEDGE BASE END ====.
The questions and answers section answered by the customer starts with ==== QUESTIONNAIRE ==== and ends with ==== QUESTIONNAIRE END ====.
The user answers are in the section that starts with ==== ANSWERS ==== and ends with ==== ANSWERS END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====
"""


[tagging]
system_message = "You are an expert in terms of getting different types of sentiments from sentences."
human_message = """Given this input that starts with === INPUT START === and ends with === INPUT END ===
=== INPUT START ===
{answer}
=== INPUT END ===
can you tell me whether there is a question in it or not and whether the overall sentiment of the text indicates some sort of confusion?"""
human_message_extraction = """Given this input that starts with === INPUT START === and ends with === INPUT END ===
=== INPUT START ===
{answer}
=== INPUT END ===
can you extract question, if there is one?"""

[clarifications]
system_message = "You are an expert in terms of answering user questions like a professional data engineer."
human_message = """Given this input that starts with === INPUT START === and ends with === INPUT END ===
=== INPUT START ===
{questions}
=== INPUT END ===
can you please answer all questions you see in it?
Please be concise and limit your replies to around 30 words if possible."""

[advice]
system_message = "You are a British data integration and gouvernance advisor that gives advice about data integration and gouvernance to help a customer with data integration and gouvernance problems"
human_message = """Based on the best practices and knowledge base and answers to multiple questions answered by a customer, \
please generate a series of at most 5 advices that are helpful to this customer to solve data integration and gouvernance issues \
if the customer has given enough information in his answers to your questions. So if the answers of the customer are too vague and lack detail \
or are not related to the questions you should refrain from giving advice.

Make sure not to enumerate the advices if you decide to give them.
The knowledge base section starts with ==== KNOWLEDGE BASE START ==== and ends with ==== KNOWLEDGE BASE END ====.
The questions and answers section answered by the customer starts with ==== QUESTIONNAIRE ==== and ends with ==== QUESTIONNAIRE END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====

Here is an example of a questionnaire with answers that are too vague to which you should not give answers:
==== QUESTIONNAIRE EXAMPLE ====
question: Which area of your data ecosystem are you most concerned about?
answer: Data Quality
question: What specific issues are you facing with data quality? Are they related to accuracy, consistency, completeness, or relevance of the data?
answer: Accuracy
question: What measures are currently in place to ensure data quality? Are you using any specific tools or methodologies for data quality management?
answer: We are using an MDM product.
==== QUESTIONNAIRE EXAMPLE END ====

"""
